name: Push

on:
    release:
        types: [published]

jobs:
    Push:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [latest]

        steps:
            - name: Set up QEMU
              uses: docker/setup-qemu-action@v2
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2
            - name: Login to Docker Hub
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}
            - name: Build and push
              uses: docker/build-push-action@v4
              with:
                  push: true
                  tags: ${{ secrets.DOCKERHUB_USERNAME }}/scandium:${{ github.sha }},${{ secrets.DOCKERHUB_USERNAME }}/scandium:latest
                  cache-from: type=gha
                  cache-to: type=gha,mode=max
